blank_issues_enabled: false
contact_links:
  - name: Questions / discussion
    url: https://github.com/lautarosegura/quill/discussions
    about: For open-ended questions, please use Discussions instead of Issues.
